"""add time

Revision ID: 3174a449f505
Revises: 62983a28da7b
Create Date: 2025-10-08 00:11:04.381302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3174a449f505'
down_revision: Union[str, Sequence[str], None] = '62983a28da7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time_minutes', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('start_time_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'start_time_hours')
    op.drop_column('events', 'start_time_minutes')
    # ### end Alembic commands ###
