"""update events schema

Revision ID: 62983a28da7b
Revises: 8f4ff4760c20
Create Date: 2025-09-09 17:54:02.486416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62983a28da7b'
down_revision: Union[str, Sequence[str], None] = '8f4ff4760c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('events', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'location_country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'location_city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'link_to_original_event',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'organizer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'add_to_calendar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('events_image_url_key'), 'events', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('events_image_url_key'), 'events', ['image_url'], postgresql_nulls_not_distinct=False)
    op.alter_column('events', 'add_to_calendar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'organizer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'link_to_original_event',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'location_city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'location_country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('events', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('events', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
