"""add time

Revision ID: 650babc9ad5f
Revises: 859627782bbf
Create Date: 2025-10-23 11:32:18.983145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650babc9ad5f'
down_revision: Union[str, Sequence[str], None] = '859627782bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('finish_time_minutes', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('finish_time_hours', sa.String(length=100), nullable=True))
    op.alter_column('events', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('events', 'start_time_minutes',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('events', 'start_time_hours',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time_hours',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('events', 'start_time_minutes',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=4),
               existing_nullable=True)
    op.alter_column('events', 'title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('events', 'finish_time_hours')
    op.drop_column('events', 'finish_time_minutes')
    # ### end Alembic commands ###
