"""time_start form int to str

Revision ID: 859627782bbf
Revises: 3174a449f505
Create Date: 2025-10-20 19:47:54.698820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859627782bbf'
down_revision: Union[str, Sequence[str], None] = '3174a449f505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    op.alter_column('events', 'start_time_hours',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'start_time_hours',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('events', 'start_time_minutes',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
