"""start & finish time

Revision ID: fb056de51958
Revises: 2a0c7d10eea4
Create Date: 2026-01-09 16:17:58.671437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb056de51958'
down_revision: Union[str, Sequence[str], None] = '2a0c7d10eea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('events', sa.Column('finish_time', sa.Time(), nullable=True))
    op.drop_column('events', 'start_time_hours')
    op.drop_column('events', 'start_time_minutes')
    op.drop_column('events', 'finish_time_minutes')
    op.drop_column('events', 'finish_time_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('finish_time_hours', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('finish_time_minutes', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('start_time_minutes', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('start_time_hours', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('events', 'finish_time')
    op.drop_column('events', 'start_time')
    # ### end Alembic commands ###
